### ISSUE TITLE
File Manager not displaying images

### ISSUE THREAD

**Issue by jfreshfield** [Siteglide/Siteglide-Admin-Feedback#4]
## Expected Behavior

Images uploaded through the File Manager, should display in the list of current images.

## Current Behavior

Newly uploaded images never appear, even after refreshing or reloading the page.

## Steps to Reproduce

1. Go to File Manager.
2. Add a new image.
3. Scroll through the image list. You will see that it does not appear in the list.
4. Refresh the page. Scroll through the list of images, to confirm that the new one isn't there.

## Environment

Windows 10 Fall Edition
Google Chrome 68.0.3440.75
Siteglide Admin v2.0.0

Example: 
* macOS 10.13.6
* Google Chrome 68.0.3440.75
* Siteglide Admin v2.0.0

**Comment by DeanmvSG** [comment]
Thanks @jfreshfield!

Just to check, do you have anymore information about the file you are uploading?  For example, file type and image size (in px)

**Comment by mattwalter91** [comment]
@jfreshfield - At the moment FileManager only shows the following file extensions:

.jpg
.jpeg
.png
.ico

We should set it up so it tells you this on upload though, rather than letting you upload the file and not see it!

I'll add support for .svg and .gif later today. Does that cover you, or was it another file type?
As Dean says, more info would be great!

**Comment by jfreshfield** [comment]
They were .png and .jpg files I was trying to upload before. Just tried it again, and I'm now able to successfully add in these types of images.

**Comment by DeanmvSG** [comment]
We made some changes to our API late last week that looks like it has done the trick!
